// REDUX ACTION TYPES
export const WEB3 = {
  LOADED: 'WEB3_LOADED',
  ACCOUNT_LOADED: 'WEB3_ACCOUNT_LOADED'
};
export const TOKEN_LOADED = 'TOKEN_LOADED';
export const EXCHANGE_LOADED = 'EXCHANGE_LOADED';
