// REDUX ACTION TYPES
export const WEB3 = {
  LOADED: 'WEB3_LOADED',
  ACCOUNT_LOADED: 'WEB3_ACCOUNT_LOADED'
};
export const TOKEN_LOADED = 'TOKEN_LOADED';
export const EXCHANGE_LOADED = 'EXCHANGE_LOADED';
export const CANCELLED_ORDERS_LOADED = 'CANCELLED_ORDERS_LOADED';
export const FILLED_ORDERS_LOADED = 'FILLED_ORDERS_LOADED';
export const ALL_ORDERS_LOADED = 'ALL_ORDERS_LOADED';
export const CANCELLING_ORDER = 'CANCELLING_ORDER';
export const ORDER_CANCELLED = 'ORDER_CANCELLED';
